eluv-io/elv-fabric-browser

- src/components/components/JSONField.js
- src/components/pages/content/ContentObject.js
- src/static/stylesheets/content.scss
Add copy button to raw version of content object version metadata.
Handle case for metadata diff where current version has no previous version.
https://user-images.githubusercontent.com/91760982/136614771-408b79d3-2b64-4f9a-902a-8f075501ab0d.mov
Button not shown on empty state
- Diff button visible for latest version when versionCount > 0 and nth version except when current version is the last in versions array.
- Copy button uses Copyable component
> Make content object version metadata copyable ; Diff case when no previous version

- src/components/components/Diff.js
Current version metadata is being passed to diff library as old data and previous version is being passed as new data. 
- Switch the order of arguments in Diff.js
> Switch argument order for metadata diff

- package.json
- src/clients/Fabric.js
- src/components/components/ContentBrowser.js
- src/components/components/ToggleSection.js
- src/components/pages/content/ContentLibrary.js
- src/components/pages/content/ContentObject.js
- src/components/pages/content/ContentObjectForm.js
- src/static/icons/search.svg
- src/static/stylesheets/app.scss
- src/static/stylesheets/content_browser.scss
- src/stores/Content.js
- src/stores/Object.js
- src/stores/index.js
Allow user to copy a content object. See associated client-js PR: https://github.com/eluv-io/elv-client-js/pull/128.
The content browser modal is identical to the one used by live-manager.
Main test cases:
- Copying an object with no encryption keys
- Copying an object with kms and user caps keys
- Copying an object with one or the other ^
- File download flow for the owner of a copied object
- File download flow for the non-owner (member of an admin group) of a copied object
- Encrypted video files successfully download and play
https://user-images.githubusercontent.com/91760982/141022944-f78c82f0-ac70-4639-bdb7-8e8b7ffb2b39.mov
https://user-images.githubusercontent.com/91760982/141022953-f1bc7718-340a-4943-9561-c5364251ce72.mov
Relates to #8 
Future improvements:
- Update sass-lint …
> Add ability to copy a content object

- src/clients/Fabric.js
- src/components/pages/content/ContentObject.js
- src/static/stylesheets/content.scss
- src/stores/Object.js
- src/utils/Helpers.js
Create section within Content Object Info that allows the owner to add and delete owner caps.
As a non-owner:
https://user-images.githubusercontent.com/91760982/142531271-a7a1dae5-e6d3-4573-bdf8-b3f6c6493301.mov
Expected/Tested
- Do not show current user cap within Encryption Keys section
- Encryption keys only viewable to non-owners (not editable)
- Users with owner cap and view/manage permissions can download/upload encrypted files
- User with view permission and no owner cap still able to access but not upload/download
- Throw error if attempting to create an owner cap before owner has a user cap
Relates to #9 
See Client PR: https://github.com/eluv-io/elv-client-js/pull/129
See Core PR: https://github.com/eluv-io/elv-core-js/pull/25
> Create owner cap management

- src/components/components/ActionsToolbar.js
- src/components/pages/access_groups/AccessGroup.js
- src/components/pages/access_groups/AccessGroupForm.js
- src/components/pages/access_groups/AccessGroupMemberForm.js
- src/components/pages/access_groups/AccessGroups.js
- src/components/pages/content/ContentApps.js
- src/components/pages/content/ContentLibraries.js
- src/components/pages/content/ContentLibrary.js
- src/components/pages/content/ContentLibraryForm.js
- src/components/pages/content/ContentLibraryTypesForm.js
- src/components/pages/content/ContentObject.js
- src/components/pages/content/ContentObjectForm.js
- src/components/pages/content/ContentObjectPartsForm.js
- src/components/pages/content/ContentObjectReviewForm.js
- src/components/pages/content/ContentTypeForm.js
- src/components/pages/content/ContentTypes.js
- src/components/pages/contracts/CompileContractForm.js
- src/components/pages/contracts/Contract.js
- src/components/pages/contracts/ContractForm.js
- src/components/pages/contracts/Contracts.js
- src/components/pages/contracts/DeployContractForm.js
- src/components/pages/contracts/WatchContractForm.js
- src/components/pages/contracts/deployed/DeployedContract.js
- src/components/pages/contracts/deployed/DeployedContractEvents.js
- src/components/pages/contracts/deployed/DeployedContractFundsForm.js
- src/components/pages/events/Events.js
- src/static/stylesheets/content.scss
- src/static/stylesheets/defaults.scss
Componentize "actions-container" code and show two actions at a time with the remaining actions in a dropdown selector. Main actions are inline with content lookup and refresh button. Addresses area of improvement outlined in https://github.com/eluv-io/elv-fabric-browser/pull/19.
Tested actions being shown as three types of users :
- Owner
- Non-owner (edit permission)
- Non-owner (access permission)
> Componentize actions toolbar and simplify

- src/clients/Fabric.js
Currently, creating a non-owner caps replaces the metadata for "/owner_caps", which throws an error when the subtree doesn't exist in the metadata.
This fix only replaces the metadata if "/owner_caps" is truthy.
> Replace metadata for owner_caps only when subtree exists

- src/clients/Fabric.js
- src/components/pages/content/ContentObject.js
- src/static/stylesheets/content.scss
- src/stores/Object.js
Address the following changes in regards to non-owner caps:
- Change "name" row header and form input to "label"
- Add "type" table column to display whether the key is an Owner/Creator type
- Convert multiformat public key when passing to CreateNonOwnerCap
- Remove "public address" from form
- Table styling changes
Tested
- Create non-owner key for new object
- Create non-owner key for object with existing keys
- Converting public key to address returns expected value
- Converting address back to public key returns expected value
> Non-owner cap form and table changes

- src/clients/Fabric.js
- src/components/pages/content/ContentLibraryForm.js
- src/stores/Library.js
Add required tenant ID field to the ContentLibraryForm, which sets tenantId in CreateContentLibrary.
The default value will set from the user tenantId metadata.
> Add tenant ID field to ContentLibraryForm

- src/clients/Fabric.js
- src/components/components/ActionsToolbar.js
- src/components/pages/content/ContentObject.js
- src/static/stylesheets/defaults.scss
Revise copy ability so that a user can copy an object ONLY if one of the following conditions is true:
a) they are the owner 
b) they have a non-owner encryption key
Additionally, make sure that the /owner_caps tree is created when the subtree doesn't exist in the metadata in the event of creating a non-owner cap.
Add disabled and title attributes to ActionsToolbar.
Testing:
1) An owner can copy an object and have playable encrypted videos
2) A non-owner with an encryption key can copy an object and have playable encrypted videos
> Revise copy content object permission, create encryption key bug

- src/components/pages/content/ContentLibraryForm.js
Load the tenant ID on load for the library edit form. Currently, the ID only loads on the create form.
> Load tenant id on load for library edit form

- src/components/components/ContentBrowser.js
- src/components/pages/content/ContentLibrary.js
- src/static/stylesheets/content_browser.scss
- src/static/stylesheets/defaults.scss
- src/stores/Content.js
- src/stores/Object.js
When copying a content object, disable objects that do not meet one of the following requirements:
1. The current user is an owner of the object
2. The current user has a user cap on the object
> Disable objects without permission when copying

- src/components/pages/content/ContentLibrary.js
- src/components/pages/content/ContentObject.js
- src/components/pages/ingest/Ingest.js
- src/router/index.js
Support ingesting media within a Library and Content Object.
Library page > More Options > Create Media Object
Library > Content Object > More Options > Convert to Media Object
Works with [elv-ingest](https://github.com/eluv-io/elv-ingest).
Library page
Object page
The library must be configured with a default abr profile and mezzanine content type via the metadata, formatted as such:
```
abr: {
default_profile: {} // object: abr profile may be copied from elv-client-js/utilities/example_files
mez_content_type: "" // string: content type version hash or title
}
```
You should now be able to see the Media Object button within More Options. Please note, the button is visible on objects that haven't yet been ingested.
> Add ingest page

- src/components/pages/content/ContentObjectForm.js
Object form fails to load on Object Create and when object typeInfo is undefined.
Set indexer tab visibility only for an existing object and add safety check for typeInfo latestType meta.
> Set indexer config tab on existing object and add safe check

- src/components/pages/content/ContentObject.js
Don't show Display tab for content objects with no offerings.
Relates to #43
> Do not show display tab for objects sans offerings

- src/clients/Fabric.js
Use `clearCache` flag on `Permission` call to update the Visibility, and ultimately, the permission in Fabric Browser.
Relates to #41 
Requires https://github.com/eluv-io/elv-client-js/pull/181
> Clear address visibility cache in Permission call

- src/components/components/ContentBrowser.js
- src/components/pages/content/ContentLibrary.js
- src/components/pages/content/ContentObject.js
- src/components/pages/content/ContentObjectForm.js
- src/components/pages/content/IndexConfiguration.js
- src/static/stylesheets/defaults.scss
- src/static/stylesheets/indexer_form.scss
- src/stores/Object.js
Add missing fields for indexer configuration:
- Query suffix
- Document prefix
- Root
- Multiple fields for `paths`
Fix issue with show_indexer_settings not properly showing/hiding Indexer tab.
Relates to #32
> Add indexer prefix, root, query fields

- src/clients/Fabric.js
- src/utils/Helpers.js
Support metadata path `/lro_draft` (no offering key suffix) and give that path precedence. 
`/lro_draft_*` paths still checked as fallback to maintain backwards compatibility.
For upcoming ingest API update I would like to switch to always using `/lro_draft` to store draft info, regardless of what the offering key is.
(For all current use cases, mezzanines only have one offering ingest active at any one time, and the offering key is stored within the reference)
e.g.:
```
{
"node": "http://localhost:8008",
"offering": "default",
"write_token": "tqw__HSWbfMeb18NzTMqXdbsweAv673uXt3vVhqn5p5PgQdaWtPR9pEKJzviLvEnnscsoNX5tVpNGA9QCCnqye4p"
}
```
Tested locally for backwards compatibility with release version of elv-client-js. Continues to show progress / status for ingests that use the present …
> Update LRO status retrieval to work with metadata path `/lro_draft`

- src/components/pages/content/ContentObject.js
Display tab should show if there is a displayAppUrl in the metadata OR if the metadata has `offerings`.
> Show display tab if displayAppUrl OR has offerings

- src/components/components/AppFrame.js
- src/components/pages/content/ContentLibrary.js
Prepend /app/Eluvio Fabric Browser path to OpenLink url change.
Also change ObjectListing key param to use state.listingVersion, which may be a reason the library objects do not completely load.
> Add full core path to OpenLink url

- src/utils/Files.js
Use File object instead of array buffer in UploadFiles() `fileInfo`. This is consistent with what is implemented in the ingest app and works.
> Fix large file uploads; use File object in place of arrayBuffer

- src/components/components/Diff.js
Enhance Diff logic. Separate functions so they're not nested, creating a new reference on each render. The `jsdiff` library offers no support for ignoring specified keys so add condition that excludes `"container": "hq__` from being returned in the added/removed changes.
> Ignore container when generating diff, separate diff logic

- src/components/components/Diff.js
Regex is not flexible enough when looking at "container": "hq__" key/values in the diff. Remove the new line from the expression.
> Fix diff container to remove new line from regex

- package-lock.json
- package.json
- src/clients/Fabric.js
- src/components/pages/access_groups/AccessGroup.js
- src/components/pages/content/ContentLibrary.js
- src/components/pages/content/ContentLibraryGroupForm.js
- src/components/pages/content/ContentObject.js
- src/components/pages/content/ContentObjectGroups.js
- src/static/stylesheets/forms.scss
- src/stores/Library.js
- src/stores/Object.js
Update labels:
Viewer -> View
Contributor -> Contribute
Reviewer -> Manage
Change checkbox inputs to radio inputs, making a single permission value selectable.
NOTE: Since library groups may have multiple permissions, I'm adhering to the current design of having multiple values in the metadata. When loading the permissions, the app will display the highest permission level found. If "reviewer" and "contributor" are found, it will save the "reviewer" value and display Manage. When saving, it will only save one value and delete any other existing permissions (applies to old group permissions).
Add remove button to the table of all group permissions:
- Content Library (new)
- Content Object (new)
- Access Group (existing/tested)
- Content Types (new)
Design note: The radio input is a new …
> Change library group permissions

- src/clients/Fabric.js
- src/components/pages/content/ContentObject.js
- src/stores/Library.js
When a user has access to an object through a group but no access to the library or content type, the Fabric Browser breaks in two ways:
- The code is looking for a property on an object that is undefined (library)
- client ContentType fails because the user doesn't have access to the content type
This adds a simple check for the library and checks the user's access rights to the content type. If they have no access, ContentType is called with the `publicOnly` flag.
> Add library safety check, use publicOnly ContentType when no user access
